"use client";

import { useState, type Dispatch, type RefObject, type SetStateAction } from "react";
import type { InlineEdit } from "../hooks/useInlinePlanEditor";
import type { ExpenseItem, ItineraryItem, LedgerItem, TripDetails } from "../model";
import type { TripPopover } from "../hooks/useTripWorkspaceView";
import { TripBudgetBoard } from "./TripBudgetBoard";
import { TripPlanBoard } from "./TripPlanBoard";
import { TripPlanDialogs } from "./TripPlanDialogs";
import { TripPrintExport } from "./TripPrintExport";
import { TripExportButton } from "./TripExportButton";
import { TripSummaryHeader } from "./TripSummaryHeader";
import { TripWorkspaceHeader } from "./TripWorkspaceHeader";
import { TripWorkspaceLayout } from "./TripWorkspaceLayout";
import { TripLibrary } from "./TripLibrary";

export type TripWorkspaceProps = {
  onMovePlan: (id: string, day: number) => void;
  onViewPlanExpenses: () => void;
  activeDay: number; budgetItems: ExpenseItem[]; coverInputRef: RefObject<HTMLInputElement | null>; days: { day: number; date: string }[]; details: TripDetails; editingPlan: ItineraryItem | null; editingRole: string | null; expenseAmount: string; expenseDate: string; expenseName: string; expenseNote: string; expensePayer: string; expenseOccurrence: "actual" | "estimated"; expenseType: ExpenseItem["type"]; expenses: LedgerItem[]; inlineEdit: InlineEdit | null; inlinePlanInputRef: RefObject<HTMLInputElement | null>; inlinePlanTextareaRef: RefObject<HTMLTextAreaElement | null>; inlineTitleInputRef: RefObject<HTMLInputElement | null>; inlineTitle: string | null; manualPlan: ItineraryItem | null; memberRoleRef: RefObject<HTMLDivElement | null>; menuRef: RefObject<HTMLDivElement | null>; newMember: string; newPlan: string; onAddPlan: () => void; onAmountChange: (value: string) => void; onDateChange: (value: string) => void; onArchive: () => void; onCoverChange: (event: React.ChangeEvent<HTMLInputElement>) => void; onCopy: (item: ItineraryItem) => void; onDelete: (id: string) => void; onDeleteTrip: () => void; onDetailsChange: (updates: Partial<TripDetails>) => void; onEdit: (item: ItineraryItem) => void; onEditBudget: (id: string) => void; onEditExpense: (id: string) => void; onInlineChange: (value: InlineEdit | null) => void; onInvite: () => void; onManualAdd: () => void; onNameChange: (value: string) => void; onNoteChange: (value: string) => void; onNewPlanChange: (value: string) => void; onOccurrenceChange: (value: "actual" | "estimated") => void; onOptimize: () => void; onPayerChange: (value: string) => void; onRelatedItineraryChange: (value: string) => void; onRemoveBudget: (id: string) => void; onRemoveExpense: (id: string) => void; onSaveEdit: (item: ItineraryItem) => void; onSaveExpense: () => void; onSaveManual: (item: ItineraryItem) => void; onSaveInline: () => void; onSelectDay: (day: number) => void; onSelectTab: (tab: "plan" | "budget") => void; onTitleChange: (value: string | null) => void; onTitleSave: () => void; onToggleExpense: () => void; onToggleMenu: (id: string) => void; onTypeChange: (value: ExpenseItem["type"]) => void; openMenuId: string | null; plans: ItineraryItem[]; popover: TripPopover; relatedItineraryItemId: string; saveStatus: "saved" | "saving" | "idle"; setEditingPlan: Dispatch<SetStateAction<ItineraryItem | null>>; setEditingRole: (name: string | null) => void; setManualPlan: Dispatch<SetStateAction<ItineraryItem | null>>; setNewMember: (value: string) => void; setPopover: Dispatch<SetStateAction<TripPopover>>; shared: boolean; shareStatus: "idle" | "copied" | "failed"; showExpense: boolean; timelineRef: RefObject<HTMLDivElement | null>; tripPopoverRef: RefObject<HTMLDivElement | null>; workspaceTab: "plan" | "budget";
};

/** Presentational boundary for the entire trip workspace; orchestration stays in its feature hook. */
export function TripWorkspace(props: TripWorkspaceProps) {
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  return <TripWorkspaceLayout collapsed={sidebarCollapsed} header={<TripWorkspaceHeader key={`${props.shared}-${props.shareStatus}`} shared={props.shared} shareStatus={props.shareStatus} />} sidebar={<TripLibrary activeDay={props.activeDay} collapsed={sidebarCollapsed} currentDetails={props.details} onCollapsedChange={setSidebarCollapsed} onMovePlan={props.onMovePlan} onSelectDay={props.onSelectDay} plans={props.plans} />}>
    <div className="trip-workspace-panel">
      <TripSummaryHeader activeTab={props.workspaceTab} coverInputRef={props.coverInputRef} details={props.details} editingRole={props.editingRole} exportButton={<TripExportButton budgetItems={props.budgetItems} days={props.days} details={props.details} expenses={props.expenses} plans={props.plans} />} inlineTitleInputRef={props.inlineTitleInputRef} inlineTitle={props.inlineTitle} memberRoleRef={props.memberRoleRef} newMember={props.newMember} onCoverChange={props.onCoverChange} onDetailsChange={props.onDetailsChange} onInvite={props.onInvite} onSelectTab={props.onSelectTab} onTitleChange={props.onTitleChange} onTitleSave={props.onTitleSave} popover={props.popover} saveStatus={props.saveStatus} setEditingRole={props.setEditingRole} setNewMember={props.setNewMember} setPopover={props.setPopover} tripPopoverRef={props.tripPopoverRef} />
      {props.workspaceTab === "plan" ? <TripPlanBoard activeDay={props.activeDay} budgetItems={props.budgetItems} expenses={props.expenses} inlineEdit={props.inlineEdit} inlineRef={props.inlinePlanInputRef} textareaRef={props.inlinePlanTextareaRef} menuRef={props.menuRef} newPlan={props.newPlan} onAddPlan={props.onAddPlan} onCopy={props.onCopy} onDelete={props.onDelete} onEdit={props.onEdit} onInlineChange={props.onInlineChange} onManualAdd={props.onManualAdd} onNewPlanChange={props.onNewPlanChange} onOptimize={props.onOptimize} onSaveInline={props.onSaveInline} onToggleMenu={props.onToggleMenu} onViewExpenses={props.onViewPlanExpenses} openMenuId={props.openMenuId} plans={props.plans} timelineRef={props.timelineRef} /> : <TripBudgetBoard budgetItems={props.budgetItems} expenseAmount={props.expenseAmount} expenseDate={props.expenseDate} expenseName={props.expenseName} expenseNote={props.expenseNote} expensePayer={props.expensePayer} expenseType={props.expenseType} expenseOccurrence={props.expenseOccurrence} expenses={props.expenses} plans={props.plans} relatedItineraryItemId={props.relatedItineraryItemId} onAmountChange={props.onAmountChange} onDateChange={props.onDateChange} onEditBudget={props.onEditBudget} onEditExpense={props.onEditExpense} onNameChange={props.onNameChange} onNoteChange={props.onNoteChange} onPayerChange={props.onPayerChange} onTypeChange={props.onTypeChange} onOccurrenceChange={props.onOccurrenceChange} onRelatedItineraryChange={props.onRelatedItineraryChange} onRemoveBudget={props.onRemoveBudget} onRemoveExpense={props.onRemoveExpense} onSaveExpense={props.onSaveExpense} onToggleExpense={props.onToggleExpense} showExpense={props.showExpense} />}
    </div>
    <TripPrintExport budgetItems={props.budgetItems} days={props.days} details={props.details} expenses={props.expenses} plans={props.plans} />
    <TripPlanDialogs activeDay={props.activeDay} days={props.days} editingPlan={props.editingPlan} manualPlan={props.manualPlan} onSaveEdit={() => props.editingPlan && props.onSaveEdit(props.editingPlan)} onSaveManual={() => props.manualPlan && props.onSaveManual(props.manualPlan)} setEditingPlan={props.setEditingPlan} setManualPlan={props.setManualPlan} />
  </TripWorkspaceLayout>;
}
