import type { ReactNode, RefObject } from "react";
import type { TripDetails } from "../model";
import { getDestinationPinyin } from "../utils";
import { TripCover } from "./TripCover";
import { TripDateEditor } from "./TripDateEditor";
import { TripMembersControl } from "./TripMembersControl";
import { TripStatusSelector } from "./TripStatusSelector";
import { TripWorkspaceControls } from "./TripWorkspaceControls";
import { useTripCapabilities } from "./TripCapabilities";

type Popover = "status" | "dates" | "members" | "settings" | null;
type Props = { accessToken: string | null; activeTab: "plan" | "budget"; coverInputRef: RefObject<HTMLInputElement | null>; details: TripDetails; editingRole: string | null; exportButton: ReactNode; inlineTitleInputRef: RefObject<HTMLInputElement | null>; inlineTitle: string | null; memberRoleRef: RefObject<HTMLDivElement | null>; newMember: string; onCoverChange: (event: React.ChangeEvent<HTMLInputElement>) => void; onDetailsChange: (patch: Partial<TripDetails>) => void; onInvite: (role: "collaborator" | "companion") => void; onSelectTab: (tab: "plan" | "budget") => void; onTitleChange: (value: string | null) => void; onTitleSave: () => void; popover: Popover; saveStatus: "idle" | "saving" | "saved"; setEditingRole: (value: string | null) => void; setNewMember: (value: string) => void; setPopover: (value: Popover | ((current: Popover) => Popover)) => void; tripId: string; tripPopoverRef: RefObject<HTMLDivElement | null> };

export function TripSummaryHeader({ accessToken, activeTab, coverInputRef, details, editingRole, exportButton, inlineTitleInputRef, inlineTitle, memberRoleRef, newMember, onCoverChange, onDetailsChange, onInvite, onSelectTab, onTitleChange, onTitleSave, popover, saveStatus, setEditingRole, setNewMember, setPopover, tripId, tripPopoverRef }: Props) {
  const { canEditTrip } = useTripCapabilities();
  return <div className="trip-head"><TripCover image={details.coverImage} inputRef={coverInputRef} label={getDestinationPinyin(details.title)} onChange={onCoverChange} /><div className="trip-meta"><div className="trip-meta-controls" ref={canEditTrip && popover === "status" ? tripPopoverRef : null}><TripStatusSelector isOpen={canEditTrip && popover === "status"} onSelect={(status) => { onDetailsChange({ status }); setPopover(null); }} onToggle={() => setPopover((current) => current === "status" ? null : "status")} status={details.status} />{saveStatus !== "idle" && <small className="save-status" role="status">{saveStatus === "saving" ? "正在保存…" : "已保存"}</small>}</div>{canEditTrip && inlineTitle !== null ? <input className="inline-title-input" ref={inlineTitleInputRef} value={inlineTitle} aria-label="行程名称" onChange={(event) => onTitleChange(event.target.value)} onBlur={onTitleSave} onKeyDown={(event) => { if (event.key === "Enter") onTitleSave(); if (event.key === "Escape") onTitleChange(null); }} /> : <h3 className="trip-title">{canEditTrip ? <button type="button" className="inline-readable" title="点击编辑行程名称" onClick={() => onTitleChange(details.title)}>{details.title}<span aria-hidden="true">✎</span></button> : details.title}</h3>}<div><TripDateEditor details={details} isOpen={canEditTrip && popover === "dates"} onChange={onDetailsChange} onToggle={() => setPopover((current) => current === "dates" ? null : "dates")} panelRef={tripPopoverRef} /><TripMembersControl accessToken={accessToken} details={details} editingRole={editingRole} isOpen={popover === "members"} newMember={newMember} onChange={onDetailsChange} onNewMemberChange={setNewMember} onToggle={() => setPopover((current) => current === "members" ? null : "members")} panelRef={tripPopoverRef} roleRef={memberRoleRef} setEditingRole={setEditingRole} tripId={tripId} /></div></div><TripWorkspaceControls activeTab={activeTab} exportButton={exportButton} onCopyInvite={onInvite} onSelectTab={onSelectTab} /></div>;
}
