import type { RefObject } from "react";
import type { ExpenseItem, ItineraryItem, LedgerItem, TripDetails } from "../model";
import type { TripPopover } from "../hooks/useTripWorkspaceView";
import { TripBudgetBoard } from "./TripBudgetBoard";
import { TripPlanBoard } from "./TripPlanBoard";
import { TripPlanDialogs } from "./TripPlanDialogs";
import { TripSummaryHeader } from "./TripSummaryHeader";
import { TripWorkspaceHeader } from "./TripWorkspaceHeader";
import { TripWorkspaceLayout } from "./TripWorkspaceLayout";
import { TripLibrary } from "./TripLibrary";

type Props = {
  onMovePlan: (id: string, day: number) => void;
  activeDay: number; budgetItems: ExpenseItem[]; coverInputRef: RefObject<HTMLInputElement | null>; days: { day: number; date: string }[]; details: TripDetails; editingPlan: ItineraryItem | null; editingRole: string | null; expenseAmount: string; expenseName: string; expenseOccurrence: "actual" | "estimated"; expenseType: ExpenseItem["type"]; expenses: LedgerItem[]; inlineEdit: { id: string; field: "title" | "note"; value: string } | null; inlineEditorRef: RefObject<HTMLInputElement | HTMLTextAreaElement | null>; inlineTitle: string | null; manualPlan: ItineraryItem | null; memberRoleRef: RefObject<HTMLDivElement | null>; menuRef: RefObject<HTMLDivElement | null>; newMember: string; newPlan: string; onAddPlan: () => void; onAmountChange: (value: string) => void; onArchive: () => void; onCoverChange: (event: React.ChangeEvent<HTMLInputElement>) => void; onCopy: (item: ItineraryItem) => void; onDelete: (id: string) => void; onDeleteTrip: () => void; onDetailsChange: (updates: Partial<TripDetails>) => void; onEdit: (item: ItineraryItem) => void; onEditBudget: (id: string) => void; onEditExpense: (id: string) => void; onInlineChange: (value: { id: string; field: "title" | "note"; value: string } | null) => void; onInvite: () => void; onManualAdd: () => void; onNameChange: (value: string) => void; onNewPlanChange: (value: string) => void; onOccurrenceChange: (value: "actual" | "estimated") => void; onOptimize: () => void; onRelatedItineraryChange: (value: string) => void; onRemoveBudget: (id: string) => void; onRemoveExpense: (id: string) => void; onSaveEdit: (item: ItineraryItem) => void; onSaveExpense: () => void; onSaveInline: () => void; onSaveManual: (item: ItineraryItem) => void; onSelectDay: (day: number) => void; onSelectTab: (tab: "plan" | "budget") => void; onTitleChange: (value: string | null) => void; onTitleSave: () => void; onToggleExpense: () => void; onToggleMenu: (id: string) => void; onTypeChange: (value: ExpenseItem["type"]) => void; openMenuId: string | null; plans: ItineraryItem[]; popover: TripPopover; relatedItineraryItemId: string; saveStatus: "saved" | "saving" | "idle"; setEditingPlan: (plan: ItineraryItem | null) => void; setEditingRole: (name: string | null) => void; setManualPlan: (plan: ItineraryItem | null) => void; setNewMember: (value: string) => void; setPopover: (popover: TripPopover) => void; shared: boolean; shareStatus: "idle" | "copied" | "failed"; showExpense: boolean; timelineRef: RefObject<HTMLDivElement | null>; tripPopoverRef: RefObject<HTMLDivElement | null>; workspaceTab: "plan" | "budget";
};

/** Presentational boundary for the entire trip workspace; orchestration stays in its feature hook. */
export function TripWorkspace(props: Props) {
  return <TripWorkspaceLayout header={<TripWorkspaceHeader onInvite={props.onInvite} shared={props.shared} shareStatus={props.shareStatus} />}>
    <div className="trip-workspace-panel">
      <TripLibrary currentDetails={props.details} />
      <TripSummaryHeader activeTab={props.workspaceTab} coverInputRef={props.coverInputRef} details={props.details} editingRole={props.editingRole} inlineEditorRef={props.inlineEditorRef} inlineTitle={props.inlineTitle} memberRoleRef={props.memberRoleRef} newMember={props.newMember} onArchive={props.onArchive} onCoverChange={props.onCoverChange} onDelete={props.onDeleteTrip} onDetailsChange={props.onDetailsChange} onInvite={props.onInvite} onSelectTab={props.onSelectTab} onTitleChange={props.onTitleChange} onTitleSave={props.onTitleSave} popover={props.popover} saveStatus={props.saveStatus} setEditingRole={props.setEditingRole} setNewMember={props.setNewMember} setPopover={props.setPopover} tripPopoverRef={props.tripPopoverRef} />
      {props.workspaceTab === "plan" ? <TripPlanBoard activeDay={props.activeDay} days={props.days} inlineEdit={props.inlineEdit} inlineRef={props.inlineEditorRef} menuRef={props.menuRef} newPlan={props.newPlan} onAddPlan={props.onAddPlan} onCopy={props.onCopy} onDelete={props.onDelete} onEdit={props.onEdit} onInlineChange={props.onInlineChange} onManualAdd={props.onManualAdd} onMovePlan={props.onMovePlan} onNewPlanChange={props.onNewPlanChange} onOptimize={props.onOptimize} onSaveInline={props.onSaveInline} onSelectDay={props.onSelectDay} onToggleMenu={props.onToggleMenu} openMenuId={props.openMenuId} plans={props.plans} timelineRef={props.timelineRef} /> : <TripBudgetBoard budgetItems={props.budgetItems} expenseAmount={props.expenseAmount} expenseName={props.expenseName} expenseType={props.expenseType} expenseOccurrence={props.expenseOccurrence} expenses={props.expenses} plans={props.plans} relatedItineraryItemId={props.relatedItineraryItemId} onAmountChange={props.onAmountChange} onEditBudget={props.onEditBudget} onEditExpense={props.onEditExpense} onNameChange={props.onNameChange} onTypeChange={props.onTypeChange} onOccurrenceChange={props.onOccurrenceChange} onRelatedItineraryChange={props.onRelatedItineraryChange} onRemoveBudget={props.onRemoveBudget} onRemoveExpense={props.onRemoveExpense} onSaveExpense={props.onSaveExpense} onToggleExpense={props.onToggleExpense} showExpense={props.showExpense} total={props.expenses.reduce((sum, item) => sum + item.amount, 0)} />}
    </div>
    <TripPlanDialogs activeDay={props.activeDay} days={props.days} editingPlan={props.editingPlan} manualPlan={props.manualPlan} onSaveEdit={props.onSaveEdit} onSaveManual={props.onSaveManual} setEditingPlan={props.setEditingPlan} setManualPlan={props.setManualPlan} />
  </TripWorkspaceLayout>;
}
